[package]
name = "job"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json", "tokio-native-tls", "blocking"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
chrono = "0.4"
futures = "0.3"

[[bin]]
name = "job"
path = "main.rs"
